trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - 'backend-spring-boot/*'
pr: none

pool:
  vmImage: 'ubuntu-18.04'

steps:
  - task: Bash@3
    displayName: 'Deploy to Heroku'
    inputs:
      targetType: 'inline'
      script: |
        git remote add heroku-backend https://heroku:$(HEROKU_API_KEY)@git.heroku.com/isa-2020-tim29-backend.git
        git push heroku-backend `git subtree split --prefix backend-spring-boot HEAD`:refs/heads/main --force