trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - 'frontend-vue-js/*'
pr: none

pool:
  vmImage: 'ubuntu-18.04'

steps:
  - task: Bash@3
    env: 
      API_KEY: $(HEROKU_API_KEY)
    displayName: 'Deploy to Heroku'
    inputs:
      targetType: 'inline'
      script: |
        git remote add heroku-frontend https://heroku:$API_KEY@git.heroku.com/isa-2020-tim29.git
        git push heroku-frontend `git subtree split --prefix frontend-vue-js HEAD`:refs/heads/main --force